### ISSUE TITLE
CLI twitter access broken

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#853] opened 2020-11-24 23:52 UTC
![image](https://user-images.githubusercontent.com/354596/100164607-4e051100-2f0c-11eb-855b-cd528b896f1a.png)

**Comment by SarveshKadam** [comment] 2020-11-25 02:54
@proful Please assign it to me. I might know the root cause of this issue

**Comment by proful** [comment] 2020-11-25 03:54
@SarveshKadam go ahead

**Closed** 2020-11-26 01:28 UTC
