### ISSUE TITLE
CLI puppetter should work with only -i option?

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#645] opened 2020-11-06 01:13 UTC
`node . -u https://twitter.com/naval/status/1002103360646823936 -p`

Not priority. But good if only need to pass ID

**Comment by johnjacobkenny** [comment] 2020-11-06 01:39
The problem is that the web scraper needs the entire URL. The api doesn't. That's why this was added now.

And imo it's a better experience to ask the user to paste the entire URL. Going forward we could consider merging both.

**Comment by PuruVJ** [comment] 2020-11-07 01:58
Closing as merged

**Closed by PuruVJ** 2020-11-07 01:58 UTC
