### ISSUE TITLE
CLI multiple thread bug

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#804] opened 2020-11-14 23:35 UTC
![image](https://user-images.githubusercontent.com/354596/99159160-4be1cc00-272e-11eb-8deb-1ad3facc648b.png)
`node . -i 1307811967428702208,1169981379620290560,1323317674466775041,1309681736079597568,1321111764851920902,1259539005097426944 -o david-perell`

@Mira-Alf 

- Error should also show which thread caused the issues.

- PDF should be created after ignoring the problematic tweet or thread

**Comment by PuruVJ** [comment] 2020-11-15 05:38
Can you set DEV=true and send the screenshot again with the full stack?

**Comment by proful** [comment] 2020-11-15 05:46
@PuruVJ why don't you run it?

**Comment by PuruVJ** [comment] 2020-11-15 05:49
Wasn't on my computer when I wrote. Am here now.

I have run it, getting the error. Looking into it.

**Comment by proful** [comment] 2020-11-15 13:23
Data not correct

**Comment by PuruVJ** [comment] 2020-11-15 13:26
What's the issue?

**Comment by Mira-Alf** [comment] 2020-11-15 14:02
* 1307811967428702208 - [OK](https://twitter.com/david_perell/status/1307811967428702208)
* 1169981379620290560 - [OK](https://twitter.com/david_perell/status/1169981379620290560)
* 1323317674466775041 - [OK](https://twitter.com/david_perell/status/1323317674466775041)
* 1309681736079597568 - [OK](https://twitter.com/david_perell/status/1309681736079597568) - last tweet is deleted by the author
* 1321111764851920902 - [OK](https://twitter.com/david_perell/status/1321111764851920902)
* 1259539005097426944 - [OK](https://twitter.com/david_perell/status/1259539005097426944)

I just checked the tweet timelines and the pdf page by page - looks Okay to me proful. Let me know what the issue is..

**Comment by PuruVJ** [comment] 2020-11-15 14:12
They all run well.

Maybe the problem is that Proful commented this just before he merged my recent PR fixing an issue, and was getting error.

**Comment by Mira-Alf** [comment] 2020-11-15 15:37
Maybe.. I pulled in your latest changes and tested.

**Closed** 2020-11-16 04:04 UTC
